name: NodeJS with Webpack and PostgreSQL

on:
  push:
    branches: [ "test-branch" ]
  pull_request:
    branches: [ "test-branch" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: mydatabase
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U myuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Wait for PostgreSQL to be ready
      run: sleep 10

    - name: Set environment variables
      run: |
        echo "DB_HOST=127.0.0.1" >> $GITHUB_ENV
        echo "DB_PORT=5432" >> $GITHUB_ENV
        echo "DB_USER=myuser" >> $GITHUB_ENV
        echo "DB_PASSWORD=mypassword" >> $GITHUB_ENV
        echo "DB_NAME=mydatabase" >> $GITHUB_ENV

    - name: Install Dependencies in Backend
      working-directory: ./backend
      run: |
        npm install

    - name: Install Dependencies in Frontend
      working-directory: ./frontend
      run: |
        npm install

    - name: Build Frontend
      working-directory: ./frontend
      run: |
        npm run build
