name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    # Backend - Solo instalación y desarrollo
    - name: Install Dependencies in Backend
      working-directory: ./backend
      run: |
        npm install

    - name: Run Backend in Development Mode
      working-directory: ./backend
      run: |
        npm run dev

    # Frontend - Instalación, construcción y desarrollo
    - name: Install Dependencies in Frontend
      working-directory: ./frontend
      run: |
        npm install

    - name: Build Frontend
      working-directory: ./frontend
      run: |
        npm run build

    - name: Run Frontend in Development Mode
      working-directory: ./frontend
      run: |
        npm run dev
